### ISSUE TITLE
Re_perl is not fully perl-compatible

### ISSUE THREAD

**Issue by samoht** [ocaml/ocaml-re#130]
It seems that `(.|\n){1000}` in perl means `(.|\n){1,1000}` in `Re_perl`. /cc @ijc25

**Comment by ijc25** [comment]
For reference, the Perl snippet I wrote when @samoht asked:
```Perl
my $data = "aaaabaaaaaaaaaaaaaaaaaaaaa";

$data =~ m/((.|\n){10})/;
print "$data\n";
print "$1\n";
```
and the output:
```sh
$ perl ~/t.pl
aaaabaaaaaaaaaaaaaaaaaaaaa
aaaabaaaaa
```

**Comment by rgrinberg** [comment]
Seems like repeating a group just means only the last group will match. E.g.

```
$ perl -e '"abc" =~ /(.){3}/; print "[$1, $2, $3]"';
[c, , ]
```

That means we should apply the `nest` combinator to the constructed group.

**Comment by ijc25** [comment]
I realised that I was wrong/mistaken in my memory of `foo{N}` when I spoke IRL to @samoht yesterday. `X{N}` is the same as `X{N,N}` (i.e matches exactly `N`) and _not_ `X{1,N}` (up to `N`) as I lead him to believe yesterday. I suspect there is therefore no bug here, sorry for the noise, not sure what happened to my brain yesterday!

(following is a bit more on the nesting of `{REPEAT}` proposed above which was written before I had the above revelation that I was being stupid... TL;DR: I think there is no bug here in this respect either...)

I don't believe groups under a `{REPEAT}` are repeated the way you seem to be suggesting, at least not with Perl style regexes. http://perldoc.perl.org/perlre.html doesn't seem to contain anything which would suggest that to me (after and admittedly quick refresher look through it).

Note that in my example `$data =~ m/((.|\n){10})/;` the outermost match is `$1`, i.e. it is more like `(.{10})` than `(.){10}`. The innermost match (AKA `$2`) is `(.|\n)` which matches the 10th letter, I think because Perl REs are greedy by default , e.g.:
```Perl
my $data = "abcdefghijklmnopqrstuvwxyz";

$data =~ m/((.|\n){10})/;
print "$data\n";
print "$1\n";
print "$2\n";
print "$3\n";
```
outputs:
```sh
$ perl ~/t.pl
abcdefghijklmnopqrstuvwxyz
abcdefghij
j

$
```

However in writing all that

**Comment by rgrinberg** [comment]
Did you finish your message?

So there's no bug right?

**Comment by ijc25** [comment]
I moved the paragraph after "However in writing all that" to the start but left the prefix, oops.

Yes, I think there is no bug.

**Comment by samoht** [comment]
Ok so closing. Thanks for making me learn some perl regexp anyway :-)
